### ISSUE TITLE
Friend API on 8081 returning 400 in docker instance

### ISSUE THREAD

**Issue by jessethach** [michaeltarleton/TripCalculator#1]
The `friend` API listening on `8081` is not working. I followed the instructions on the README using `docker-compose up`. Are there any steps that are missing in the README?

<img width="1197" alt="screen shot 2019-01-02 at 8 40 15 am" src="https://user-images.githubusercontent.com/10701395/50601954-b48d6b80-0e6a-11e9-90dd-b461be0bc8da.png">

**Comment by michaeltarleton** [comment]
I’ll take a look this evening.

**Comment by michaeltarleton** [comment]
The error was caused by Elasticsearch not being "ready" when the TripCalculatorService attempted to seed the data.

The fix was to add Reactive Extensions to manage the retry and delay for both the backend service call to Elasticsearch and the frontend call to the backend service.

**Comment by michaeltarleton** [comment]
@jessethach ^^^

**Comment by jessethach** [comment]
Great! I'll update my local. I'll let you know if I run into further issues.

**Comment by jessethach** [comment]
@michaeltarleton It looks like I am running into the same issue:

<img width="1188" alt="screen shot 2019-01-03 at 11 00 36 am" src="https://user-images.githubusercontent.com/10701395/50656062-d65c2080-0f46-11e9-8ada-e31adac31410.png">

Am I supposed to run the service separately?

**Comment by michaeltarleton** [comment]
Can you try a re-clone of master?

**Comment by michaeltarleton** [comment]
I’m going to try it on a different machine in about 5 minutes.

**Comment by michaeltarleton** [comment]
Ok, it worked for me on another computer so I think I know what issue you are having is...

You will need to re-build the service so try: `docker-compose up --build`

**Comment by michaeltarleton** [comment]
@jessethach ^^^

**Comment by jessethach** [comment]
@michaeltarleton Yup! That was it - project is now running. Thanks for the walkthrough!
